name: blogify
description: Explore, learn, and share on our blog app.
publish_to: 'eserdeiro'
version: 0.1.1+3

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  equatable: ^2.0.5
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_riverpod: ^2.4.9
  formz: ^0.6.1
  go_router: ^13.0.1
  http: ^1.2.0
  image_picker: ^1.0.7
  recaptcha_enterprise_flutter: ^18.4.1
  timeago: ^3.6.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

# flutter_native_splash:
#   color: "#FFFFFF"
#   image: lib/assets/images/icons/icon-960-circular.png
#   android_12:
#     image: lib/assets/images/icons/icon-960-circular.png
#     color: "#FFFFFF"
#   android: true
#   ios: true
#   web: false
flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/icons/
    - lib/assets/fonts/

  fonts:
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
