name: blogify
description: A new Flutter project.
publish_to: 'eserdeiro'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_riverpod: ^2.4.9
  formz: ^0.6.1
  go_router: ^13.0.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/fonts/

  fonts:
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
